services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
  bull-monitor:
    image: ejhayes/nodejs-bull-monitor:2.2.0
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - BULL_COLLECT_QUEUE_METRICS_INTERVAL_MS=5000
      # - UI=bull-master
      - UI=bull-board
      - BULL_WATCH_QUEUE_PREFIXES=bull
    ports:
      - "3002:3000"
    depends_on:
      - redis

volumes:
  postgres_data: