global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "media-scraper-api"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["media-scraper-service:3001"]
        labels:
          service: "media-scraper"
          component: "api"

  - job_name: "media-scraper-worker"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["media-scraper-service:3010"]
        labels:
          service: "media-scraper"
          component: "worker"
